[versions]
koin-bom = "4.1.1"
configurate = "4.2.0"

[libraries]
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
configurate-extra-kotlin = {module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate"}

[bundles]
configurate = [ "configurate-hocon", "configurate-extra-kotlin" ]